version: "3"
services:
  pihole:
    container_name: pihole
    domainname: homedomain.lan
    restart: unless-stopped 
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
#      - "0.0.0.0:443:443/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: 192.168.77.77
#      ServerIPv6: fd77:1234:5678:77:96c6:91ff:fea4:c6a3
      TZ: Europe/Berlin
      WEBPASSWORD: admin
      DNS1: 217.0.43.49
      DNS2: 8.8.8.8
      # IPv6 Address if your network supports it
      #ServerIPv6: 192.168.1.55
      # jwilder/proxy envs, see readme for more info
#      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.homedomain.lan
#      VIRTUAL_PORT: 80
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      #   Point any of the jwilder virtual_host addresses
      # to your docker host ip address
      - 'pihole.homedomain.lan:192.168.77.77'
    volumes:
      - '/var/pihole/:/etc/pihole/'
      # WARNING: if this log don't exist as a file on the host already
      # docker will try to create a directory in it's place making for lots of errors
#      - '/var/log/pihole.log:/var/log/pihole.log'
