version: "3"
services:
  tvheadend:
    container_name: tvheadend
    restart: unless-stopped 
    image: nirvana777/tvheadend
    network_mode: host
#    ports:
#      - "19981:9981/tcp"
#      - "19982:9982/tcp"
    environment:
      PUID: 1004
      PGID: 44
#      RUN_OPTS: -C -u tvheadend -g video
      TZ: Europe/Berlin
    volumes:
      - /mnt/hdd3/video/recordings/:/recordings
      - /var/tvheadend/:/config
#      - '/mnt/hdd3/video/recordings/:/recordings'
    devices:
      - '/dev/dri:/dev/dri'
