version: "3"
services:
  vpn_schweiz:
    image: nirvana777/nordvpn:latest
    container_name: vpn_schweiz
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    env_file: ~/env/nordvpn.env
    environment:
      - CONNECT=Switzerland
      - TECHNOLOGY=OpenVPN
      - OBFUSCATE=Enable
      - NETWORK=192.168.77.0/24
      - TZ=Europe/Berlin
    ports:
      - "8180:8180"
      - "8181:8181"
    restart: unless-stopped

  telerising-zattoo:
    container_name: telerising-zattoo
    restart: unless-stopped 
    image: takealug/telerising-api:latest
    depends_on:
      - vpn_schweiz
    network_mode: "service:vpn_schweiz"     
    env_file:
      - /home/tvheadend/env/zattoo.env
    environment:
      - USER_ID=1004
      - GROUP_ID=44
      - PROVIDER=zattoo.com
      - UPDATE=no
      - PORT=8180
      - BW=5000
      - PROFILE=1
      - AUDIO2=true
      - DOLBY=true
      - TZ=Europe/Berlin
      - SSL_MODE=1
    volumes:
      - /var/docker/telerising/zattoo/:/telerising
    tmpfs:
      - /tmp
      - /var/log      

  telerising-wilmaa:
    container_name: telerising-wilmaa
    restart: unless-stopped 
    image: takealug/telerising-api:latest
    depends_on:
      - vpn_schweiz
    network_mode: "service:vpn_schweiz"     
    env_file:
      - /home/tvheadend/env/wilmaa.env
    environment:
      - USER_ID=1004
      - GROUP_ID=44
      - PROVIDER=wilmaa.com
      - UPDATE=no
      - PORT=8181
      - BW=5000
      - PROFILE=1
      - AUDIO2=true
      - DOLBY=true
      - TZ=Europe/Berlin
      - SSL_MODE=1
    volumes:
      - /var/docker/telerising/wilmaa/:/telerising
    tmpfs:
      - /tmp
      - /var/log      
